apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: llanesleonardo
  description: Personal for Leonardo Llanes
spec:
  type: guest
  profile:
    displayName: Leonardo Llanes
  members: []
